# Titanic Project Config File

# This data set only contains the features we want to use,
# and with title extracted from the name variable:

# data:
TITANIC_DATA: 'https://www.openml.org/data/get_csv/16826755/phpMYEkMl'
SAVE_RAW_DATA: True
TITANIC_RAW: '../data/titanic_raw.csv'

SAVE_DATA_POST_ETL: True
TITANIC_POST_ETL: '../data/titanic_post_etl.csv'

SAVE_TRAIN_TEST_DATA: True
TITANIC_X_TRAIN: '../data/titanic_training_data.csv'
TITANIC_X_TEST: '../data/titanic_testing_data.csv'

TITANIC_SCALER: '../models/scaler.pkl'
TITANIC_MODEL: '../models/model.pkl'

# general:
TARGET: survived
FEATURES:
  - pclass
  - age
  - sex
  - sibsp
  - parch
  - fare
  - cabin
  - embarked
  - title

# ETL pre-processing:
NUMERICAL_TO_FLOAT:
  - age
  - fare

# model pre-processing:
NUMERICAL_TO_IMPUTE:
  - age
  - fare
NUMERICAL_TO_SCALE:
  - age
  - fare
CATEGORICAL_WITH_MISSING_VALUES:
  - cabin
  - embarked
CATEGORICAL_WITH_RARE_LABELS:
  - cabin
  - title
DICT_OF_FREQUENT_LABELS:
  cabin:
    - C
    - Missing
  title:
    - Miss
    - Mr
    - Mrs
